version: 0.2

phases:
  pre_build:
    commands:
      - account=$(aws sts get-caller-identity --query Account --output text)
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${account}.dkr.ecr.us-east-1.amazonaws.com 
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...    
      - cd docker
      - docker build -t anomalyimage:latest .
      - docker tag anomalyimage:latest ${account}.dkr.ecr.us-east-1.amazonaws.com/anomalyimage:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${account}.dkr.ecr.us-east-1.amazonaws.com/anomalyimage:latest
artifacts:
  name: ${account}.dkr.ecr.us-east-1.amazonaws.com/anomalyimage:latest

  